version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - go
      - Skip Changelog
    assignees:
      - "tillkuhn"
      - "pschulten"
    open-pull-requests-limit: 10

