name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
#        platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Cache Go modules packages
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Build
        run: go build ./...

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Test
        run: go test
